#!/bin/sh
#

load_drivers()
{
	while IFS= read -r line; do
		modprobe $line
	done < "/etc/modules.conf"
}

case "$1" in
	start)
		printf "Loading modules "
		load_drivers
		echo "OK"
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
