#!/bin/sh

case "$1" in
  start)

#    echo ds2482 0x18 > /sys/bus/i2c/devices/i2c-0/new_device
#    echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-0/new_device
#    hwclock -s
    date

    analogclock -platform linuxfb:fb="/dev/fb1" &
    ;;
  stop)
    ;;
  restart)
     stop
     start
     echo
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0



