#!/bin/sh

case "$1" in
  start)
    analogclock -platform linuxfb:fb="/dev/fb1" &
	;;
  stop)
	;;
  restart)
	 stop
	 start
	echo
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0



