#!/bin/sh

file1="/usr/bin/analogclock"
file2="/usr/bin/dashboard"

case "$1" in
  start)
    if [[ -x "$file2" ]]
    then
      $file2 -platform linuxfb:fb="/dev/fb1" &
    else
      if [[ -x "$file1" ]]
      then
        $file1 -platform linuxfb:fb="/dev/fb1" &
      fi
    fi
    ;;
  stop)
    ;;
  restart)
     stop
     start
     echo
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0



