SPHINXBASE2_VERSION=0.6.1
SPHINXBASE2_SOURCE=sphinxbase-$(SPHINXBASE2_VERSION).tar.gz
SPHINXBASE2_SITE=http://downloads.sourceforge.net/project/cmusphinx/sphinxbase/$(SPHINXBASE2_VERSION)
SPHINXBASE2_AUTORECONF = NO
SPHINXBASE2_INSTALL_STAGING = YES
SPHINXBASE2_INSTALL_TARGET = YES
SPHINXBASE2_CONF_OPTS = --without-python
SPHINXBASE2_INSTALL_STAGING_OPTS = DESTDIR=$(STAGING_DIR) LDFLAGS=-L$(STAGING_DIR)/usr/lib install

$(eval $(autotools-package))
